title: La Scatola Bianca
description: Gioco fantasy medievale d'avventura
remote_theme: pmarsceill/just-the-docs
aux_links:
  "La Scatola Bianca su GitHub":
    - "//github.com/Italian-Translation-Alliance/la-scatola-bianca"
  "Versione PDF":
    - "//ita-translation-alliance.itch.io/la-scatola-bianca"
  "lulu":
    - "//www.lulu.com/en/en/shop/alessio-persichetti-and-roberto-bisceglie/la-scatola-bianca/paperback/product-qqj8rn.html?page=1&pageSize=4"
  "amazon":  