title: La Scatola Bianca
description: Gioco fantasy medievale d'avventura
remote_theme: pmarsceill/just-the-docs
aux_links:
  "La Scatola Bianca su GitHub":
    - "//github.com/Italian-Translation-Alliance/la-scatola-bianca"